// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/chroma-redesign/Current.tsx": () => import("../components/mockups/chroma-redesign/Current.tsx"),
  "./components/mockups/chroma-redesign/MacOS.tsx": () => import("../components/mockups/chroma-redesign/MacOS.tsx")
};
